### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by gelisam**
Most of the fields in Rendering.State was dead code, so I removed it.

After removing all the dead code, all that remained of `State` was a record with a single field, the texture cache. So I replaced the record with that texture cache, and I replaced the `state` variables with `cachedTexture` everywhere, including in the comments. I haven't touched the many other types which are also called `State`.

### CODE REVIEW

**Comment by gelisam** [comment]
Oh, is that the same `State` which my previous pull request exposed? Better not rename it then, as it would break some code.

**Comment by gelisam** [comment]
Removed the commit which renamed `state` to `cachedTexture`, instead `State` is still a record with only one field.

**Comment by benl23x5** [comment]
Thanks for the patches, I'll address all of these and make a new release once GHC 7.10 is properly out.

**Comment by benl23x5** [comment]
Exported initState, but left the render options in. Having the render options is helpful for debugging, and they don't seem to have any related bugs.

**Pull request closed without merging**
