### PR TITLE
Split off bitmap example as a first step towards separating the examples...

### PR DESCRIPTION
**Pull request by patrikja**
... into a bag of independent hackage packages.

I failed to build the full gloss-examples package due to some llvm problem and I'm preparing for helping out with a [beginners course](https://github.com/juliajansson/gitbeginner/blob/master/2014-12-29.md) using gloss and Haskell where installation problems should be avoided (and examples need not be so complex). 

I just tried separating the first example executable to start with. There may very well be a clear separation into just two example groups - if so, a hint would be appreciated.

### CODE REVIEW

**Comment by patrikja** [comment]
Now boids is also a separate cabal package.
Note that I have not yet updated the cabal version number.

**Comment by patrikja** [comment]
By now I have split off six packages:
gloss-examples-bitmap
gloss-examples-clock
gloss-examples-easy
gloss-examples-boids
gloss-examples-conway
gloss-examples-eden

**Comment by patrikja** [comment]
Now I'm at a stage when all the small packages gloss-examples-* build separately but all the remaining gloss-examples/ seem to depend on gloss-render which fails to build.
The examples are already more than enough for the course so I'll stop here.

**Comment by patrikja** [comment]
Ping (;-)

**Comment by patrikja** [comment]
Ping!

**Comment by benl23x5** [comment]
Sorry, I didn't see this pull request until now. I don't check github front page every day, and I turned status update emails off. Best way to contact me is via email.

I don't think splitting gloss-examples into so many packages is a good idea because 1) It pollutes the Hackage package namespace; 2) It increases the maintenance burden, because I'd need to maintain all the separate cabal files; 3) To make it easy to install all the examples we'd need to add yet another package on top that imports all of them.

If you just want to avoid compiling some examples with -fllvm then you should be able to add a flag to the cabal package so that some examples can be turned off, or compilation via llvm can be disabled. Eg: see: https://www.haskell.org/cabal/users-guide/developing-packages.html#configurations. You could also add a flag to the install of gloss-raster to disable LLVM.

I don't want to add a boatload more packages to the repo just to control whether a compiler flag is enabled or not.

**Comment by patrikja** [comment]
I see.
All I want is a version of the current gloss-examples which installs for
"newbies". If this can be achieved by changing some flag, fine, but
otherwise splitting into gloss-examples-X and gloss-examples-Y where one of
them installs easily would be of great help.

/Patrik


2015-02-13 6:00 GMT+01:00 Ben Lippmeier <notifications@github.com>:

**Comment by benl23x5** [comment]
The existing gloss.cabal file demonstrates how to use the cabal flag mechanism. We've got flags to enable and disable GLUT and GLFW. I wouldn't mind adding a flag to turn off LLVM.

https://hackage.haskell.org/package/gloss-1.9.2.1/gloss.cabal

**Pull request closed without merging**
